version: '3.9'
services:
  web:
    build:
      context: .
      args:
        - DATABASE_URL=postgres://postgres:secret@postgres
    ports:
      - '8000:5000'
    environment:
      DATABASE_URL: 'postgres://postgres:secret@postgres'
      NODE_ENV: production
    depends_on:
      - postgres
  postgres:
    image: 'postgres:alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
